### ISSUE TITLE
Ongoing: Ideas for better moderation functionality

### ISSUE THREAD

**Issue by Sopsy** [LautaMedia/YBoard#2]
Mainly for current moderators of Ylilauta. Please give your ideas on how to make our moderation functionality the greatest ever.

**Comment by kusipillupaska** [comment]
Ilmiantosivu: 
>ilmiantosivulle ilmiannetun postaajan vuorokauden postausten lukumäärä (mahdollisesti pelkkiin roskapostitus tai jokin muu syy-ilmoituksiin?)
>ip-osoitteen taustaväri arpoutuu 4chanin tripcode-tyylisesti eri väriseksi ja näyttää duplikaatit samalla värikoodilla
>erillinen nappi yhden viestin poistamiselle ja useammalle viestille
>tarkistetut ilmiannot järjestyksessä tarkistusajan (viimeisin uusimmaksi) tai filtteröinnin mukaan
>filtteröinti. esim. alalaudan, sääntörikkomystyypin tjsp. mukaan
>ilmiannon päälle viedessä tooltip kertoo kuinka monta ilmiantoa käyttäjästä tai kuinka monta ilmiannettua kohdetta käyttäjällä on

Muuta:
>vitusti banaanijäbää
![1433188797544](https://cloud.githubusercontent.com/assets/21989633/18233315/62994680-72ec-11e6-8d92-711a540899ac.png)
